<template>
  <section class="section">
    <prismic-rich-text
      v-if="slice.primary.title"
      :field="slice.primary.title"
    />
    <h1 v-else>TextSlice</h1>
    <p>Hey I'm your new slice 🍕I've been generated by SliceMachine.</p>
    <p v-if="endpoint">
      Or pass me props
      <a target="_blank" :href="endpoint">in your writing room</a>
    </p>
  </section>
</template>
<script>
export default {
  props: ["slice"],
  computed: {
    endpoint() {
      return this.$prismic && this.$prismic.apiEndpoint
        ? this.$prismic.apiEndpoint
            .split("/")
            .slice(0, -2)
            .join("/")
            .replace("cdn.", "")
        : null;
    }
  }
};
</script>
<style scoped>
.section {
  position: relative;
  background: #ffff63;
  color: #111;
  padding: 4em;
  text-align: center;
}
a {
  color: #111;
}
</style>
